### ISSUE TITLE
There is no "serializer" service

### ISSUE THREAD

**Issue by jakub-zawislak** [Limenius/LiformBundle#14]
Docs says:

> This bundle registers a normalizer to serialize forms with errors into an array.

```php
$serializer = $this->get('serializer');
$initialValues = $serializer->normalize($form);
```

but there is no "serializer" service registered. I see in `services.yml` that there is `InitialValuesNormalizer`
```xml
<service id="liform.serializer.initial_values_normalizer" class="Limenius\Liform\Serializer\Normalizer\InitialValuesNormalizer" public="false">
  <tag name="serializer.normalizer" priority="-10" />
</service>
```
but it is `public="false"` so I can't access it.

I have eneded with this:
```php
$normalizer = new \Limenius\Liform\Serializer\Normalizer\InitialValuesNormalizer();
$initialValues = $normalizer->normalize($form);
```

**Comment by VictoriaQ** [comment]
This was fixed in f96cd655e91eedd5588cd31291c6ba04b20a7f27
