### ISSUE TITLE
New release please

### ISSUE THREAD

**Issue by umpirsky** [Limenius/LiformBundle#19]
Can we get a new release? The latest one is missing https://github.com/Limenius/LiformBundle/commit/f96cd655e91eedd5588cd31291c6ba04b20a7f27 latest Symfony compatibility fix.

Thanks.

**Comment by umpirsky** [comment]
Ping @nacmartin. :)

**Comment by VictoriaQ** [comment]
There is a new release v0.13.0. Thanks for the ping.

**Comment by stevanradovanovic** [comment]
Hey guys,

can we get a new release? The latest one is missing [b46ba76](https://github.com/Limenius/Liform/commit/b46ba76cc7703b9d9989ff9f8ca4437cfc8f6c6c) CSRF token fix.

cc./ @VictoriaQ 

Thanks!
